apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: gcp-cluster
  region: us-east-1
  version: "1.34"
nodeGroups:
  - name: ramalama-gpu-workers
    instanceType: g6.xlarge
    ami: ami-096d79104714a752d
    amiFamily: Ubuntu2204
    minSize: 1
    desiredCapacity: 1
    maxSize: 1
    volumeSize: 100
    overrideBootstrapCommand: |
      #! /bin/bash
      source /var/lib/cloud/scripts/eksctl/bootstrap.helper.sh
      /etc/eks/bootstrap.sh ${CLUSTER_NAME} --container-runtime containerd --kubelet-extra-args "--node-labels=${NODE_LABELS}"
    ssh:
      allow: true
      publicKeyPath: ~/.ssh/id_rsa.pub
